---
version: 1
interactions:
- request:
    body: <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>fr-par</LocationConstraint></CreateBucketConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;host;x-amz-acl;x-amz-content-sha256;x-amz-date,
        Signature=7593cf5c5f6dc8ef03d42e6817b014d1b0f8337dd1541b5f7d4c43ddf1fe511e
      Content-Length:
      - "150"
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - 2cb57fad7b7168921a4c94426cfcb9ee2953f126430595df844e22d50f029060
      X-Amz-Date:
      - 20210518T131658Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Tue, 18 May 2021 13:16:59 GMT
      Location:
      - /test-acc-scaleway-object-bucket-cors-empty-origin
      X-Amz-Id-2:
      - txb756a8e8f44441c282aa9-0060a3be4a
      X-Amz-Request-Id:
      - txb756a8e8f44441c282aa9-0060a3be4a
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-md5;host;x-amz-acl;x-amz-content-sha256;x-amz-date,
        Signature=8016b60c56a84e8137d0dbf28884cd185aaa8abb9a6551fbf7e9ce698b479a16
      Content-Md5:
      - 1B2M2Y8AsgTpgAmY7PhCfg==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20210518T131659Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?acl=
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Tue, 18 May 2021 13:16:59 GMT
      X-Amz-Id-2:
      - tx415d831eb43f441c84965-0060a3be4b
      X-Amz-Request-Id:
      - tx415d831eb43f441c84965-0060a3be4b
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=62dc1dc33a93912b90a04976fdbbf32d3bddc2b07aafda11024c626fe9695aa2
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131659Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx71ba9e6ea0bf408f8d6c8-0060a3be4b</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:16:59 GMT
      X-Amz-Id-2:
      - tx71ba9e6ea0bf408f8d6c8-0060a3be4b
      X-Amz-Request-Id:
      - tx71ba9e6ea0bf408f8d6c8-0060a3be4b
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=62dc1dc33a93912b90a04976fdbbf32d3bddc2b07aafda11024c626fe9695aa2
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131659Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx165ff16eb2aa482cabd22-0060a3be4d</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:01 GMT
      X-Amz-Id-2:
      - tx165ff16eb2aa482cabd22-0060a3be4d
      X-Amz-Request-Id:
      - tx165ff16eb2aa482cabd22-0060a3be4d
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=62dc1dc33a93912b90a04976fdbbf32d3bddc2b07aafda11024c626fe9695aa2
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131659Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txc7a248e320ea444fae68e-0060a3be51</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:05 GMT
      X-Amz-Id-2:
      - txc7a248e320ea444fae68e-0060a3be51
      X-Amz-Request-Id:
      - txc7a248e320ea444fae68e-0060a3be51
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=62dc1dc33a93912b90a04976fdbbf32d3bddc2b07aafda11024c626fe9695aa2
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131659Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx9c55ab2d6f104ba0a3fe3-0060a3be59</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:13 GMT
      X-Amz-Id-2:
      - tx9c55ab2d6f104ba0a3fe3-0060a3be59
      X-Amz-Request-Id:
      - tx9c55ab2d6f104ba0a3fe3-0060a3be59
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=2d12559f4d05bea9a194c7cc0a39ff0ed30c8a65aa93fa3736efbf4987f0c69a
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131713Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx426ad08978dc4ebc93920-0060a3be59</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:14 GMT
      X-Amz-Id-2:
      - tx426ad08978dc4ebc93920-0060a3be59
      X-Amz-Request-Id:
      - tx426ad08978dc4ebc93920-0060a3be59
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=2d12559f4d05bea9a194c7cc0a39ff0ed30c8a65aa93fa3736efbf4987f0c69a
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131713Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx240013d31d72408d957c6-0060a3be5c</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:16 GMT
      X-Amz-Id-2:
      - tx240013d31d72408d957c6-0060a3be5c
      X-Amz-Request-Id:
      - tx240013d31d72408d957c6-0060a3be5c
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=2d12559f4d05bea9a194c7cc0a39ff0ed30c8a65aa93fa3736efbf4987f0c69a
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131713Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx335e3cb188734b4cb1d43-0060a3be60</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:20 GMT
      X-Amz-Id-2:
      - tx335e3cb188734b4cb1d43-0060a3be60
      X-Amz-Request-Id:
      - tx335e3cb188734b4cb1d43-0060a3be60
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=2d12559f4d05bea9a194c7cc0a39ff0ed30c8a65aa93fa3736efbf4987f0c69a
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131713Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txe4b0867e05604bbab320a-0060a3be68</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:28 GMT
      X-Amz-Id-2:
      - txe4b0867e05604bbab320a-0060a3be68
      X-Amz-Request-Id:
      - txe4b0867e05604bbab320a-0060a3be68
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=1e74a0b76a83fc7f163d519208b41d8f3e99afc2f62ef509b8258c70d66d15ce
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131728Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txde18f2cf205e4ab0b61ea-0060a3be68</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:28 GMT
      X-Amz-Id-2:
      - txde18f2cf205e4ab0b61ea-0060a3be68
      X-Amz-Request-Id:
      - txde18f2cf205e4ab0b61ea-0060a3be68
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=1e74a0b76a83fc7f163d519208b41d8f3e99afc2f62ef509b8258c70d66d15ce
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131728Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx163cb9041c3a497184c50-0060a3be6a</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:30 GMT
      X-Amz-Id-2:
      - tx163cb9041c3a497184c50-0060a3be6a
      X-Amz-Request-Id:
      - tx163cb9041c3a497184c50-0060a3be6a
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=1e74a0b76a83fc7f163d519208b41d8f3e99afc2f62ef509b8258c70d66d15ce
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131728Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txe24f0252b6ca426791b1b-0060a3be6e</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:34 GMT
      X-Amz-Id-2:
      - txe24f0252b6ca426791b1b-0060a3be6e
      X-Amz-Request-Id:
      - txe24f0252b6ca426791b1b-0060a3be6e
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=1e74a0b76a83fc7f163d519208b41d8f3e99afc2f62ef509b8258c70d66d15ce
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131728Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txb1012a0c66c34cfd831e6-0060a3be76</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:42 GMT
      X-Amz-Id-2:
      - txb1012a0c66c34cfd831e6-0060a3be76
      X-Amz-Request-Id:
      - txb1012a0c66c34cfd831e6-0060a3be76
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=8b815806ad0528287ce0bf3271ea153010cf38c44df3e5b7295ca5427723cb1e
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131743Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx36a27fc0197043af8bba2-0060a3be77</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:44 GMT
      X-Amz-Id-2:
      - tx36a27fc0197043af8bba2-0060a3be77
      X-Amz-Request-Id:
      - tx36a27fc0197043af8bba2-0060a3be77
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=8b815806ad0528287ce0bf3271ea153010cf38c44df3e5b7295ca5427723cb1e
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131743Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txb027f2f72ba3409d8fe85-0060a3be7a</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:46 GMT
      X-Amz-Id-2:
      - txb027f2f72ba3409d8fe85-0060a3be7a
      X-Amz-Request-Id:
      - txb027f2f72ba3409d8fe85-0060a3be7a
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=8b815806ad0528287ce0bf3271ea153010cf38c44df3e5b7295ca5427723cb1e
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131743Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txa36c38d0726c4a5a8213a-0060a3be7e</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:50 GMT
      X-Amz-Id-2:
      - txa36c38d0726c4a5a8213a-0060a3be7e
      X-Amz-Request-Id:
      - txa36c38d0726c4a5a8213a-0060a3be7e
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=8b815806ad0528287ce0bf3271ea153010cf38c44df3e5b7295ca5427723cb1e
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20210518T131743Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txa0bfa0cc378e4a31b6a91-0060a3be86</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Tue, 18 May 2021 13:17:58 GMT
      X-Amz-Id-2:
      - txa0bfa0cc378e4a31b6a91-0060a3be86
      X-Amz-Request-Id:
      - txa0bfa0cc378e4a31b6a91-0060a3be86
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWJ9FJYVF1SPS9HX0VZ/20210518/fr-par/s3/aws4_request,
        SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5568e7b986cfdde4e8e103bfb394c640f7ed8ed737f642b38279d27ce98b74ab
      User-Agent:
      - aws-sdk-go/1.38.22 (go1.15.11; linux; amd64)
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20210518T131758Z
    url: https://test-acc-scaleway-object-bucket-cors-empty-origin.s3.fr-par.scw.cloud/
    method: DELETE
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Tue, 18 May 2021 13:17:59 GMT
      X-Amz-Id-2:
      - tx0627cac6adff4b5ab61c0-0060a3be86
      X-Amz-Request-Id:
      - tx0627cac6adff4b5ab61c0-0060a3be86
    status: 204 No Content
    code: 204
    duration: ""
