---
version: 1
interactions:
- request:
    body: <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>fr-par</LocationConstraint></CreateBucketConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;host;x-amz-acl;x-amz-content-sha256;x-amz-date,
        Signature=bf1cdd84321309fa3d80758c6ab152bcf9d84419d4c77ba7861954aebae68119
      Content-Length:
      - "150"
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - 2cb57fad7b7168921a4c94426cfcb9ee2953f126430595df844e22d50f029060
      X-Amz-Date:
      - 20211105T171032Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Fri, 05 Nov 2021 17:10:34 GMT
      Location:
      - /bucket-1028700368552748993
      X-Amz-Id-2:
      - tx9b22e5d38e204a0a923ce-0061856588
      X-Amz-Request-Id:
      - tx9b22e5d38e204a0a923ce-0061856588
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-md5;host;x-amz-acl;x-amz-content-sha256;x-amz-date,
        Signature=4bdf81a11562fe3c99061b58e032665c725560e7139eb0cf5a3be5e4183cbe9a
      Content-Md5:
      - 1B2M2Y8AsgTpgAmY7PhCfg==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20211105T171034Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?acl=
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Fri, 05 Nov 2021 17:10:34 GMT
      X-Amz-Id-2:
      - txe49599fe0ab740eabd202-006185658a
      X-Amz-Request-Id:
      - txe49599fe0ab740eabd202-006185658a
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=38d209367220dd821ec80e5ba0be88d760fff7f23e895d868d3e25b33e4f0a98
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171034Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx7a68dc0119424f96932c9-006185658a</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:34 GMT
      X-Amz-Id-2:
      - tx7a68dc0119424f96932c9-006185658a
      X-Amz-Request-Id:
      - tx7a68dc0119424f96932c9-006185658a
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=38d209367220dd821ec80e5ba0be88d760fff7f23e895d868d3e25b33e4f0a98
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171034Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx2ecd1549a5434aea8df97-006185658c</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:36 GMT
      X-Amz-Id-2:
      - tx2ecd1549a5434aea8df97-006185658c
      X-Amz-Request-Id:
      - tx2ecd1549a5434aea8df97-006185658c
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=38d209367220dd821ec80e5ba0be88d760fff7f23e895d868d3e25b33e4f0a98
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171034Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx04d9d6e877644042ae923-0061856590</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:40 GMT
      X-Amz-Id-2:
      - tx04d9d6e877644042ae923-0061856590
      X-Amz-Request-Id:
      - tx04d9d6e877644042ae923-0061856590
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=38d209367220dd821ec80e5ba0be88d760fff7f23e895d868d3e25b33e4f0a98
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171034Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx1ce228853571438e9e951-0061856598</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:48 GMT
      X-Amz-Id-2:
      - tx1ce228853571438e9e951-0061856598
      X-Amz-Request-Id:
      - tx1ce228853571438e9e951-0061856598
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=d8dfa9fd6d4a9e2bea26cb39731b39b489f731843774976655c40ff8a9691fea
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171048Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx04b0578b26674daf9dccd-0061856598</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:49 GMT
      X-Amz-Id-2:
      - tx04b0578b26674daf9dccd-0061856598
      X-Amz-Request-Id:
      - tx04b0578b26674daf9dccd-0061856598
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=d8dfa9fd6d4a9e2bea26cb39731b39b489f731843774976655c40ff8a9691fea
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171048Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txeaa7cabf58ea4ca9a6e3f-006185659b</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:51 GMT
      X-Amz-Id-2:
      - txeaa7cabf58ea4ca9a6e3f-006185659b
      X-Amz-Request-Id:
      - txeaa7cabf58ea4ca9a6e3f-006185659b
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=d8dfa9fd6d4a9e2bea26cb39731b39b489f731843774976655c40ff8a9691fea
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171048Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txe987a6ce9389486f9e891-006185659f</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:10:55 GMT
      X-Amz-Id-2:
      - txe987a6ce9389486f9e891-006185659f
      X-Amz-Request-Id:
      - txe987a6ce9389486f9e891-006185659f
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=d8dfa9fd6d4a9e2bea26cb39731b39b489f731843774976655c40ff8a9691fea
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171048Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txb1ab10aaeb2e431593538-00618565a7</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:04 GMT
      X-Amz-Id-2:
      - txb1ab10aaeb2e431593538-00618565a7
      X-Amz-Request-Id:
      - txb1ab10aaeb2e431593538-00618565a7
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=88fb1924172c458dd33f8b44dac9d337fe2a0135a62e68c7ad725dcd81e2a7c8
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171104Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx3acdc3c1fd474dcbb23f7-00618565a8</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:04 GMT
      X-Amz-Id-2:
      - tx3acdc3c1fd474dcbb23f7-00618565a8
      X-Amz-Request-Id:
      - tx3acdc3c1fd474dcbb23f7-00618565a8
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=88fb1924172c458dd33f8b44dac9d337fe2a0135a62e68c7ad725dcd81e2a7c8
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171104Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx1bc9feb890ed41e4bd23b-00618565aa</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:06 GMT
      X-Amz-Id-2:
      - tx1bc9feb890ed41e4bd23b-00618565aa
      X-Amz-Request-Id:
      - tx1bc9feb890ed41e4bd23b-00618565aa
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=88fb1924172c458dd33f8b44dac9d337fe2a0135a62e68c7ad725dcd81e2a7c8
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171104Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx5828be33f9b24a31ade79-00618565ae</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:10 GMT
      X-Amz-Id-2:
      - tx5828be33f9b24a31ade79-00618565ae
      X-Amz-Request-Id:
      - tx5828be33f9b24a31ade79-00618565ae
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=88fb1924172c458dd33f8b44dac9d337fe2a0135a62e68c7ad725dcd81e2a7c8
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171104Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx9ca92cedf2f648c2a7f04-00618565b6</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:18 GMT
      X-Amz-Id-2:
      - tx9ca92cedf2f648c2a7f04-00618565b6
      X-Amz-Request-Id:
      - tx9ca92cedf2f648c2a7f04-00618565b6
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=e028fce450703708b1d19039ef717b5665bb3164e63ebd23fb2d07bb9af0d65d
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171118Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txe7a8b492f1294311964f4-00618565b6</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:18 GMT
      X-Amz-Id-2:
      - txe7a8b492f1294311964f4-00618565b6
      X-Amz-Request-Id:
      - txe7a8b492f1294311964f4-00618565b6
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=e028fce450703708b1d19039ef717b5665bb3164e63ebd23fb2d07bb9af0d65d
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171118Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx412dc9c6f89f4180b239a-00618565b8</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:21 GMT
      X-Amz-Id-2:
      - tx412dc9c6f89f4180b239a-00618565b8
      X-Amz-Request-Id:
      - tx412dc9c6f89f4180b239a-00618565b8
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=e028fce450703708b1d19039ef717b5665bb3164e63ebd23fb2d07bb9af0d65d
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171118Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx2f6e630b8a7e4c048fdbb-00618565bd</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:25 GMT
      X-Amz-Id-2:
      - tx2f6e630b8a7e4c048fdbb-00618565bd
      X-Amz-Request-Id:
      - tx2f6e630b8a7e4c048fdbb-00618565bd
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,
        Signature=e028fce450703708b1d19039ef717b5665bb3164e63ebd23fb2d07bb9af0d65d
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20211105T171118Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx86d85e74653c407c8650e-00618565c5</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Fri, 05 Nov 2021 17:11:33 GMT
      X-Amz-Id-2:
      - tx86d85e74653c407c8650e-00618565c5
      X-Amz-Request-Id:
      - tx86d85e74653c407c8650e-00618565c5
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      Authorization:
      - AWS4-HMAC-SHA256 Credential=SCWF4BF54P0CRPCKJRZN/20211105/fr-par/s3/aws4_request,
        SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=abed8412c1d4ad8be55937a4bf5e74e192bdd4e1a8efaeeed0ea4a2ec657587d
      User-Agent:
      - aws-sdk-go/1.41.16 (go1.17.1; darwin; amd64)
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20211105T171133Z
    url: https://bucket-1028700368552748993.s3.fr-par.scw.cloud/
    method: DELETE
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Fri, 05 Nov 2021 17:11:34 GMT
      X-Amz-Id-2:
      - tx23435700aac243df81655-00618565c5
      X-Amz-Request-Id:
      - tx23435700aac243df81655-00618565c5
    status: 204 No Content
    code: 204
    duration: ""
