---
version: 1
interactions:
- request:
    body: <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>fr-par</LocationConstraint></CreateBucketConfiguration>
    form: {}
    headers:
      Content-Length:
      - "150"
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - 2cb57fad7b7168921a4c94426cfcb9ee2953f126430595df844e22d50f029060
      X-Amz-Date:
      - 20221027T124525Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Thu, 27 Oct 2022 12:45:33 GMT
      Location:
      - /test-acc-scaleway-object-cors-empty-origin-4964789044009298413
      X-Amz-Id-2:
      - tx9f35ca6466284d24b4839-00635a7d6a
      X-Amz-Request-Id:
      - tx9f35ca6466284d24b4839-00635a7d6a
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      Content-Md5:
      - 1B2M2Y8AsgTpgAmY7PhCfg==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Acl:
      - private
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20221027T124533Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?acl=
    method: PUT
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Thu, 27 Oct 2022 12:45:33 GMT
      X-Amz-Id-2:
      - tx95884af809c44cb6be390-00635a7d6d
      X-Amz-Request-Id:
      - tx95884af809c44cb6be390-00635a7d6d
    status: 200 OK
    code: 200
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124533Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx340e0b4df0534eb9b1633-00635a7d6d</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:33 GMT
      X-Amz-Id-2:
      - tx340e0b4df0534eb9b1633-00635a7d6d
      X-Amz-Request-Id:
      - tx340e0b4df0534eb9b1633-00635a7d6d
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124533Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx5403d10b41e8475eab01b-00635a7d6f</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:35 GMT
      X-Amz-Id-2:
      - tx5403d10b41e8475eab01b-00635a7d6f
      X-Amz-Request-Id:
      - tx5403d10b41e8475eab01b-00635a7d6f
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124533Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txaca491f031604acb91aa8-00635a7d73</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:39 GMT
      X-Amz-Id-2:
      - txaca491f031604acb91aa8-00635a7d73
      X-Amz-Request-Id:
      - txaca491f031604acb91aa8-00635a7d73
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124533Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx816a8d8950934dd3b4c22-00635a7d7c</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:48 GMT
      X-Amz-Id-2:
      - tx816a8d8950934dd3b4c22-00635a7d7c
      X-Amz-Request-Id:
      - tx816a8d8950934dd3b4c22-00635a7d7c
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124548Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txe889465b61e849d382f09-00635a7d7c</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:48 GMT
      X-Amz-Id-2:
      - txe889465b61e849d382f09-00635a7d7c
      X-Amz-Request-Id:
      - txe889465b61e849d382f09-00635a7d7c
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124548Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx3dd8e07d62ad4889b4519-00635a7d7e</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:50 GMT
      X-Amz-Id-2:
      - tx3dd8e07d62ad4889b4519-00635a7d7e
      X-Amz-Request-Id:
      - tx3dd8e07d62ad4889b4519-00635a7d7e
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124548Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx3787a2e3880143a48e5cc-00635a7d83</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:45:55 GMT
      X-Amz-Id-2:
      - tx3787a2e3880143a48e5cc-00635a7d83
      X-Amz-Request-Id:
      - tx3787a2e3880143a48e5cc-00635a7d83
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124548Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx25e1b6ad526a429483ab0-00635a7d8b</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:03 GMT
      X-Amz-Id-2:
      - tx25e1b6ad526a429483ab0-00635a7d8b
      X-Amz-Request-Id:
      - tx25e1b6ad526a429483ab0-00635a7d8b
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124603Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txf058e70e448d4952a8937-00635a7d8c</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:04 GMT
      X-Amz-Id-2:
      - txf058e70e448d4952a8937-00635a7d8c
      X-Amz-Request-Id:
      - txf058e70e448d4952a8937-00635a7d8c
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124603Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txab1af52e31974a22a0bdc-00635a7d8e</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:06 GMT
      X-Amz-Id-2:
      - txab1af52e31974a22a0bdc-00635a7d8e
      X-Amz-Request-Id:
      - txab1af52e31974a22a0bdc-00635a7d8e
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124603Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txf8da5396d7e94f97834cd-00635a7d92</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:10 GMT
      X-Amz-Id-2:
      - txf8da5396d7e94f97834cd-00635a7d92
      X-Amz-Request-Id:
      - txf8da5396d7e94f97834cd-00635a7d92
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124603Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx166f17fda34b4db4af8ae-00635a7d9a</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:19 GMT
      X-Amz-Id-2:
      - tx166f17fda34b4db4af8ae-00635a7d9a
      X-Amz-Request-Id:
      - tx166f17fda34b4db4af8ae-00635a7d9a
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124619Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx16625d4448a847a584252-00635a7d9b</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:19 GMT
      X-Amz-Id-2:
      - tx16625d4448a847a584252-00635a7d9b
      X-Amz-Request-Id:
      - tx16625d4448a847a584252-00635a7d9b
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124619Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>tx570b4327147343cf9c394-00635a7d9d</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:21 GMT
      X-Amz-Id-2:
      - tx570b4327147343cf9c394-00635a7d9d
      X-Amz-Request-Id:
      - tx570b4327147343cf9c394-00635a7d9d
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124619Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txab94021433bf49e19293b-00635a7da2</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:26 GMT
      X-Amz-Id-2:
      - txab94021433bf49e19293b-00635a7da2
      X-Amz-Request-Id:
      - txab94021433bf49e19293b-00635a7da2
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedHeader>*</AllowedHeader><AllowedMethod>PUT</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedOrigin></AllowedOrigin><ExposeHeader>x-amz-server-side-encryption</ExposeHeader><ExposeHeader>ETag</ExposeHeader><MaxAgeSeconds>3000</MaxAgeSeconds></CORSRule></CORSConfiguration>
    form: {}
    headers:
      Content-Length:
      - "365"
      Content-Md5:
      - doCaNFYhpSrVvrLN1cQaiQ==
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - 62ab1c45dea8e5ff7f728bddc81ca0c025fba503d0afd2a0f282657162c2dcbe
      X-Amz-Date:
      - 20221027T124619Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/?cors=
    method: PUT
  response:
    body: |-
      <?xml version='1.0' encoding='UTF-8'?>
      <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>txd40d04d6bff446eab1856-00635a7dab</RequestId><Reason>'NoneType' object has no attribute 'count'</Reason></Error>
    headers:
      Content-Type:
      - application/xml
      Date:
      - Thu, 27 Oct 2022 12:46:35 GMT
      X-Amz-Id-2:
      - txd40d04d6bff446eab1856-00635a7dab
      X-Amz-Request-Id:
      - txd40d04d6bff446eab1856-00635a7dab
    status: 500 Internal Server Error
    code: 500
    duration: ""
- request:
    body: ""
    form: {}
    headers:
      User-Agent:
      - aws-sdk-go/1.44.110 (go1.19.1; linux; amd64)
      X-Amz-Content-Sha256:
      - e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      X-Amz-Date:
      - 20221027T124635Z
    url: https://test-acc-scaleway-object-cors-empty-origin-4964789044009298413.s3.fr-par.scw.cloud/
    method: DELETE
  response:
    body: ""
    headers:
      Content-Length:
      - "0"
      Content-Type:
      - text/html; charset=UTF-8
      Date:
      - Thu, 27 Oct 2022 12:46:36 GMT
      X-Amz-Id-2:
      - txbf093c413e97480db3375-00635a7dab
      X-Amz-Request-Id:
      - txbf093c413e97480db3375-00635a7dab
    status: 204 No Content
    code: 204
    duration: ""
